### ISSUE TITLE
Project list with their technologies and status

### ISSUE THREAD

**Issue by eddiejaoude** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#1]
Project list to have the following information

- project title
- project link
- main project maintainers / point of contact
- status (idea, started, mature, maintenance)
- technologies used

What else?

**Comment by BOLT04** [comment]
In terms of the UI I would suggest a project picture (or perhaps gif 🤔...) so the user can get a feel for the project even before clicking the link to see more. 

**Example**:
![imagem](https://user-images.githubusercontent.com/18630253/90769419-1faddf00-e2e8-11ea-9856-828208c0cc0d.png)

Source: https://aromalanil.me/#portfolio

**Comment by eddiejaoude** [comment]
Project preview/screenshot is a great idea 👍

**Comment by ritvij14** [comment]
![image](https://user-images.githubusercontent.com/51456744/91307972-44b0bf00-e7cc-11ea-8641-dc251fbca73e.png)

This is the current look of the Projects section, I have kept it simple but responsive.

**Comment by eddiejaoude** [comment]
Looks good, sharing a responsive image too would be useful

**Comment by alrifay** [comment]
Should we close this issue since we now have a project list and create a new issue for each missing feature?

**Comment by BOLT04** [comment]
I think that is a good idea @alrifay 👍. We can separate each task so that each contributor has less work to do, which generates a smaller and easier to review PR. There might be merge issues to solve after, but nothing we can't manage 😄 

Missing features:
- main project maintainers / point of contact
- status (idea, started, mature, maintenance)
- technologies used

**Comment by eddiejaoude** [comment]
Yep good idea 👍
