### ISSUE TITLE
HomePage project section could use more testing.

### ISSUE THREAD

**Issue by AllanRegush** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#81]
I think the homepage could use more testing. We should make sure project cards have are what we are expecting.

**Comment by AllanRegush** [comment]
I would like to tackle this. Any input on cypress best practices would be appreciated. Do we put these tests in homepage.feature?

**Comment by BOLT04** [comment]
Hi @AllanRegush, yes I think they would go to homepage.feature, but @Karem1986 can provide more input about this topic 😃

**Comment by eddiejaoude** [comment]
Thanks @AllanRegush 

I think with the automated testing, it is good to have a balance with how detailed we go with it, otherwise it will be very difficult to maintain. 

Some of my ideas:

- Check each section exists, probably title
- Check each section for the correct card count, for example, there are 8 project cards
- Test 1 card for each section that has the content we expect - this shows the card component is working
- Check footer links

I am open to ideas / suggestions too 🤓

**Comment by Karem1986** [comment]
Hi everyone,
I will do the testing with Cypress, although not right now. I am happy to walk you through Allan. 
Karem

**Comment by BOLT04** [comment]
I agree with @eddiejaoude ideas. I have a few notes to add that I think we should consider when developing these tests:
- Don't test specific content on the page (e.g. checking if the title of a card is "EddieBot"), since this data may change in the future and that shouldn't require a change to tests, imo
- Test if the layout of each card shows less data on mobile (e.g. moderator card only has links and hides some text)
