### ISSUE TITLE
 Project list to show technologies used

### ISSUE THREAD

**Issue by Shanmuganathanb** [EddieJaoudeCommunity/EddieJaoudeCommunity.github.io#91]
Let people know the technologies used in the project..

**Comment by BOLT04** [comment]
I'd like to work on this 😃. If anyone else is also interested in this issue let me know 👍 

My idea is to have a list of icons below the description of each project. The goal would be to occupy less space, so instead of putting "TypeScript", it would be the TypeScript logo/icon.

I've also considered an approach like GitHub, where we show a color and then the technology name:
![imagem](https://user-images.githubusercontent.com/18630253/95019376-ee515e80-065c-11eb-88cf-be7ce23ea382.png)

I'm no expert on UI/UX, so please do give me your opinion by commenting below 😃
